<a href="https://colab.research.google.com/github/vksgm/ML_hands_on/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
print(np.__version__)

2.0.2




> **Attribues of array**



THUMB RULE

---
In NUMPY() for a 2D matrix, Rows means vertical axis(axis=0) and moving downwards ( across columns )
Columns means horizontal axis.(axis=1) and moving left to right ( across rows )

In NumPy arrays with more than two dimensions, the last two values in the shape tuple generally represent the rows and columns, respectively.

Eg. for Image the shape of the Tensor will be like
Image_Shape = ( Height, Width, Channels )

here channels is RGB colors.


In [ ]:
#Attributes of ndarray
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],dtype=np.int32)
#Returns shape tuple
print(a.shape)
#returns as length of the shape will be equal to the dimension( axis ) of array
print('The shape is',len(a.shape))
#dimension
print('The dimension is', a.ndim)
#size--> total elements in array
print('The size is', a.size)
#dtype of array: note this will be homogenous array always
print(a.dtype)
#The total item size of the array( size of each element in array)
print(a.itemsize)
#type of the variable
print(type(a))
#complex type array
ai = np.array([[1,-2],[3,4]],dtype=complex)
print(ai)

(3, 4)
The shape is 2
The dimension is 2
The size is 12
int32
4
<class 'numpy.ndarray'>
[[ 1.+0.j -2.+0.j]
 [ 3.+0.j  4.+0.j]]


**Array Creation**

In [ ]:
#zero array
# NOTE: !!  By default, the dtype of the created array is float64 but we can explicility specify the dtype while creation
b = np.zeros(2)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.strides) #defines the total byte size to navigate to numpy array

[0. 0.]
(2,)
2
1
(8,)


In [ ]:
#Empty Array with 2 elements
#The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!
#the empty array content will be random
c = np.empty(2,dtype=np.int64)
print(c)
print(c.shape)
print(c.size)
print(c.ndim)

c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)


[              1 140735183323136]
(2,)
2
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
#Array with range of elements with specifying float datatype
d = np.arange(4, dtype=np.float64)
print(d)
print(d.shape)
print(d.size)
print(d.ndim)

[0. 1. 2. 3.]
(4,)
4
1


In [ ]:
#1s array
b = np.ones(3)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)

[1. 1. 1.]
(3,)
3
1


In [ ]:
#Step size ( initialval, finalval, step size)
#Note: We cannot create a ND array directly using the arange() operator.
# We need to use reshape.
e = np.arange(2, 9, 2)
print(e)
e1 = np.linspace(2,10, num=5,dtype=int)
print(e1)
sin=np.linspace(0, 2 * 3.14, 100) #multiple small points
print(sin)

[2 4 6 8]
[ 2  4  6  8 10]
[0.         0.06343434 0.12686869 0.19030303 0.25373737 0.31717172
 0.38060606 0.4440404  0.50747475 0.57090909 0.63434343 0.69777778
 0.76121212 0.82464646 0.88808081 0.95151515 1.01494949 1.07838384
 1.14181818 1.20525253 1.26868687 1.33212121 1.39555556 1.4589899
 1.52242424 1.58585859 1.64929293 1.71272727 1.77616162 1.83959596
 1.9030303  1.96646465 2.02989899 2.09333333 2.15676768 2.22020202
 2.28363636 2.34707071 2.41050505 2.47393939 2.53737374 2.60080808
 2.66424242 2.72767677 2.79111111 2.85454545 2.9179798  2.98141414
 3.04484848 3.10828283 3.17171717 3.23515152 3.29858586 3.3620202
 3.42545455 3.48888889 3.55232323 3.61575758 3.67919192 3.74262626
 3.80606061 3.86949495 3.93292929 3.99636364 4.05979798 4.12323232
 4.18666667 4.25010101 4.31353535 4.3769697  4.44040404 4.50383838
 4.56727273 4.63070707 4.69414141 4.75757576 4.8210101  4.88444444
 4.94787879 5.01131313 5.07474747 5.13818182 5.20161616 5.26505051
 5.32848485 5.39191919 5.45535354 5.5

Calling via Function

In [ ]:
def f(x, y):          # Defining the function
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int) # calling the function
b
b[2, 3]
b[0:5, 1]  # each row in the second column of b
b[:, 1]    # equivalent to the previous example
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

**Array Manupulation**

In [ ]:
#Sorting of array
#numpy.sort(a, axis=-1, kind=#sorting algo, order=None, *, stable=None)
#Sorting returns the copy of the array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr) # Ascending order


#Concatenate---NEED MORE DETAILS--!!


In [ ]:
#Array Reshaping
import numpy as np
a = np.arange(6)
print('original Array', a)
print('Original Dimension', a.ndim)
print('Original Shape', a.shape)
b=a.reshape(3,2)
print('Reshaped',b)
print('Reshaped Dimension',b.ndim)
#diff bt C order and F order ???
print('Re-shaping with C' )
print(np.reshape(a, (2,3), order='C'))
print('Re-shaping with A(Fortan)' )
c= np.reshape(a, (2,3), order='A')
d=np.zeros_like(c) #create a similar array of C dimension
print(d)
print('Reshaped Dimension',c.ndim)
# i couldnt get how the dimension is calculated here!!:)

original Array [0 1 2 3 4 5]
Original Dimension 1
Original Shape (6,)
Reshaped [[0 1]
 [2 3]
 [4 5]]
Reshaped Dimension 2
Re-shaping with C
[[0 1 2]
 [3 4 5]]
Re-shaping with A(Fortan)
[[0 0 0]
 [0 0 0]]
Reshaped Dimension 2


**Conversion of dimensions of array**

In [ ]:
#np.newaxis to create a new axis/Dimension
a=np.arange(6)
print(a.shape)
#convert a 1D to row vector ( row vector also 2D?)
print('1D vector Details')
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)
print(row_vector.ndim)
print('2D vector Details')
row_vector2=row_vector[np.newaxis,:]#again adding 1 more dimension
print(row_vector2.shape) #3 dimension here

print(row_vector2)
print(row_vector2.ndim)

#np.expand_dims to add an axis at a specified(0) index
expand=np.expand_dims(row_vector2,axis=0)
print('the expanded array',expand)
print('the expanded dimension at 0th index is', expand.ndim)

#np.expand_dims to add an axis at a specified (1) index
expand=np.expand_dims(row_vector2,axis=1)
print('the expanded array',expand)
print('the expanded dimension at 1th index is', expand.ndim)


(6,)
1D vector Details
(1, 6)
[[0 1 2 3 4 5]]
2
2D vector Details
(1, 1, 6)
[[[0 1 2 3 4 5]]]
3
the expanded array [[[[0 1 2 3 4 5]]]]
the expanded dimension at 0th index is 4
the expanded array [[[[0 1 2 3 4 5]]]]
the expanded dimension at 1th index is 4


Upload real image

In [ ]:
from PIL import Image
import numpy as np

# Load your image (replace 'your_image.jpg' with the path to your image)
img = Image.open( r'/content/Image.jpg')

# Convert the image to RGB (if it's not already)
img = img.convert('RGB')

# Convert the image to a NumPy array
arr = np.array(img)

# Check the shape of the array
print(arr.shape)  # This will show (Height, Width, 3) for an RGB image

#save the file to view in real
# We cannot save the 3D. so we need to convert it to 2D image
#
np.savetxt('Image_file_640*640.csv', arr) #save the format


(640, 640, 3)


ValueError: Expected 1D or 2D array, got 3D array instead

**Indexing and Slicing**

In [ ]:
#indexing
a=np.arange(6)
print(a)
print(a[1])
print(a[0:2])
#printing from 1 to end of the array
print(a[1:])
# In Python (and NumPy), negative indexing starts from the end of the array
print(a[-1])
#printing from starting to 2nd index ( 3 wont be considered )
print('Print start to end index', a[:3])
#print with conditions
print(a[a<4])
cond = a[(a>1) & (a<4)]
print('mulitple conditions:',a[cond])

#return boolean values when returning only the conditions
cond=(a>1) & (a<4)
print('Returning boolean values',cond)

# checking the value in array
not_there = np.nonzero(a == 3)
print('Checking the value',not_there)

#Nonzero property
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=np.nonzero(a<5)
#it returns the values where the a<5 in tuple for each dimension.
#we need to plot the co.ordinates to get the positions
print(b)
#plot the co.ordinates( first zip it !!)
list_of_coordinates=list(zip(b[0], b[1]))
for coord in list_of_coordinates:
  print('the co.ordinates are',coord)


a= np.arange(10)**3 # printing the cube for 10 values
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(a)
print(a[-1]) #print the last element


[0 1 2 3 4 5]
1
[0 1]
[1 2 3 4 5]
5
Print start to end index [0 1 2]
[0 1 2 3]
mulitple conditions: [2 3]
Returning boolean values [False False  True  True False False]
Checking the value (array([3]),)
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
the co.ordinates are (np.int64(0), np.int64(0))
the co.ordinates are (np.int64(0), np.int64(1))
the co.ordinates are (np.int64(0), np.int64(2))
the co.ordinates are (np.int64(0), np.int64(3))
[1000    1 1000   27 1000  125  216  343  512  729]
729


**Creat Array from Existing Array**

In [ ]:
#stacking of array
#stacking the arrays
x = np.arange(1,5,1)
x_stacked = np.stack([x, x, x, x], dim=0)
print('stack at dimension 0',x_stacked)
y_stacked = np.stack([x, x, x], dim=1)
print('stack at dimension 1',y_stacked)
#vertical stacking
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print('Vertical Stacking')
print(np.vstack((a1,a2)))
#Horizontal Stacking
print('Horizontal Stacking')
print(np.hstack((a1,a2)))

#Splitting of array
s1=np.arange(1,25).reshape(2,12)
print('Splitting of array of equal size')
print(s1)
#splitting into 3 equal arrays (Note: only it can split to equal arrays,else error)
print(np.hsplit(s1,4))

#splitting at specific column(s) here at 3rd and 4th
print('Splitting at 3rd and 4th columns',np.hsplit(s1,(3,4)))



Vertical Stacking
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
Horizontal Stacking
[[1 1 3 3]
 [2 2 4 4]]
Splitting of array of equal size
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]
Splitting at 3rd and 4th columns [array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


**Squeezing of Arrays**

**Copying of Arrays**

In [ ]:
#Views in Array
#Note views modifies the original record also( whenever slicing or any operation is done, it used view inside)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#stored in b1 view
b1 = a[0, :]
print(b1)
#modifiying the record in view
b1[0] = 99
b1
#it modifies the original array 'a'
print(a[0])
print('-------------------')
#Copy function
b2=b1.copy()
print(b2)
#copy doesnt affect the original (b1)
b2[0]=100
print('Copied',b2)
print('Original',b1)

[1 2 3 4]
[99  2  3  4]
-------------------
[99  2  3  4]
Copied [100   2   3   4]
Original [99  2  3  4]


**Basic Array Operations**
It occurs elementwise~

In [ ]:
#Addition
import numpy as np
a1=np.ones(2,dtype=int)
a2=np.array([1,2])
print(a1+a2)
#Subtraction
print(a1-a2)
#Multiplication
print(a1*a2)
#Division
print(a1/a2)
#------------------
#Sum Operation to find the total of array
print('the total sum is',a1.sum())

#Sum at specific axis
b=np.array([[1,6],
            [3,4]])
print('Vertical Axis Comparision)',b.sum(axis=0))
print('Horizontal Comparision',b.sum(axis=1))

#max
print('The max is',b.max())
print('the max in (Vertical Axis))',b.max(axis=0))
print('the max in (Horizontal Axis))',b.max(axis=1))
#min
print('the minimum is',b.min())
print('the minimum in Vertical Axis))',b.min(axis=0))
print('the minimum in Horizontal Axis))',b.min(axis=1))

#change data type
c = np.array([1, 2, 3], dtype=int)
c_float = c.astype(float)
print(c_float)

[2 3]
[ 0 -1]
[1 2]
[1.  0.5]
the total sum is 2
Vertical Axis Comparision) [ 4 10]
Horizontal Comparision [7 7]
The max is 6
the max in (Vertical Axis)) [3 6]
the max in (Horizontal Axis)) [6 4]
the minimum is 1
the minimum in Vertical Axis)) [1 4]
the minimum in Horizontal Axis)) [1 3]
[1. 2. 3.]


**Type UpCasting**

In [ ]:

#When operating with arrays of different types,
#the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

a = np.ones(3, dtype=np.int32)  # Integer type
b = np.linspace(0, 3.14, 3)  # float type
b.dtype.name
c = a + b
c
c.dtype.name  # will be float as considered as generic type that supports a & b
d = np.exp(c * 1j)
d
d.dtype.name


'complex128'

**Matrix Operations ( Element wise and entire matrix wise )**

In [ ]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print('Element wise multiplication',A * B)     # elementwise product

# Matrix wise product
#Result (0, 0): (1 * 2) + (1 * 3) = 5
#Result (0, 1): (1 * 0) + (1 * 4) = 4
#Result (1, 0): (0 * 2) + (1 * 3) = 3
#Result (1, 1): (0 * 0) + (1 * 4) = 4
print('Matrix Multiplication',A @ B )     # matrix product
print('another matrix multiplication',A.dot(B))  # another matrix product
print('Another way :)',np.matmul(A,B))

Element wise multiplication [[2 0]
 [0 4]]
Matrix Multiplication [[5 4]
 [3 4]]
another matrix multiplication [[5 4]
 [3 4]]


**Broadcasting Arrays**

In [ ]:
#Broadcasting means Arithmetic operations ( of different sizes )

#success case
a = np.array([[1, 2, 3]])  # Shape: (1, 3)
b = np.array([[10], [20], [30]])  # Shape: (3, 1)

result = a + b
print(result)
print(result.shape)

#Failure case
a = np.array([[1, 2, 3]])  # Shape: (1,3)
b = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)

try:
    result = a + b
    print(result)
except ValueError as e: #valueerror is the exception thrown when shape mismatches in broadcasting
    print(f"Broadcasting error: {e}")

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data.shape)
print(ones_row.shape)
print('Different shape broadcasting',data + ones_row)



[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
Broadcasting error: operands could not be broadcast together with shapes (1,3) (2,2) 
(3, 2)
(1, 2)
Different shape broadcasting [[2 3]
 [4 5]
 [6 7]]


**Creating Matrices**

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print('fetching 0th row 1st column',data[0,1]) #fetching 0th row 1st column
print('fetching from 1st row and till 2nd row',data[1:3]) #fetching from 1st row and till 2nd row
print('fetching from 0 to 1 rows and 0th column',data[0:2,0]) #fetching from 0 to 1 rows and 0th column
print('Max value',data.max())
print('Min Value',data.min())
print('Column Max',data.max(axis=0)) #Column_Max
print('Row Max',data.max(axis=1)) #Row_Max



[[1 2]
 [5 3]
 [4 6]]
fetching 0th row 1st column 2
fetching from 1st row and till 2nd row [[5 3]
 [4 6]]
fetching from 0 to 1 rows and 0th column [1 5]
Max value 6
Min Value 1
Column Max [5 6]
Row Max [2 5 6]


**Random Generator**
Note:The rng.random() function in NumPy is designed to generate random numbers from a continuous uniform distribution over the interval [0.0, 1.0).
To represent numbers from a continuous distribution within a specific range, floating-point numbers (floats) are the natural choice.

In [ ]:
from numpy.random import default_rng
rng=default_rng()
#Random array
rng.random(3)
#random range with seed 40(to get the same result again seed value is used) and shape (2,3)
print(default_rng(40).random((2,3)))
#Random matrix
rng.random((3,2))
#Random integers between zero and 5
random_array = rng.integers(0, 5, size=5)
print(random_array)
# Generate a 2x3 matrix of random integers between -5 (inclusive) and 5 (exclusive)
random_matrix = rng.integers(-5, 5, size=(2, 3))
print(random_matrix)
#to make the higher number inclusive, then set the endpoint='true'
random_matrix = rng.integers(-5, 5, size=(2, 3),endpoint='true')
print(random_matrix)


[[0.7298985  0.69341496 0.94192102]
 [0.05965206 0.69052097 0.92239752]]
[2 0 1 0 2]
[[ 2 -1 -1]
 [-4  2 -2]]
[[ 1 -5  5]
 [ 4 -2  5]]


**Uniqueness in array**

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
#Print Unique values( when no other params are mentioned, return will be in SORTED ORDER)
unique_values = np.unique(a)
#returns the first matching index of the unique values using return_index flag
indices_list = np.unique(a, return_index=True)
#to get frequency count of unique values
occurance_count = np.unique(a, return_counts=True)
print('Unique Values list',unique_values)
print('Unique Value index list',indices_list)
print('Unique Values frequency count',occurance_count)

#Uniqueness in 2D array
a_2d = np.array([[5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
print('Default Sorted',np.unique(a_2d))
unique_rows = np.unique(a_2d, axis=0)
print('Unique Rows',unique_rows) # Default sorted when no return params are used
a_2d_c = np.array([[4,1],[6,0]])
row_sum = np.sum(a_2d_c, axis=0)
print('X-Axis sum', row_sum)
col_sum = np.sum(a_2d_c, axis=1)
print('Y-Axis sum', col_sum)

#Uniquess in Axis
a_2d_c= np.array([[4,1],
                  [4,1]])
unique_x = np.unique(a_2d_c, axis=0)
unique_y = np.unique(a_2d_c, axis=1)
print('Unique Vertical axis',unique_x)
#NOTE -!!! UNIQUE COLUMNS ( AXIS = 1 ) doesnt work as expected.
print('Unique Horizontal Axis',unique_y)

Unique Values list [11 12 13 14 15 16 17 18 19 20]
Unique Value index list (array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))
Unique Values frequency count (array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))
Default Sorted [ 1  2  3  4  5  6  7  8  9 10 11 12]
Unique Rows [[ 1  2  3  4]
 [ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
X-Axis sum [10  1]
Y-Axis sum [5 6]
Unique Vertical axis [[4 1]]
Unique Horizontal Axis [[1 4]
 [1 4]]


**Transposing and Reversal the Matrix**

Note: See how Transposing works for 3D array


In [ ]:
#Matrix Transpose
arr = np.arange(6).reshape((2, 3))
print('Original Array',arr)
print('Transposed Array',arr.T)
print(arr.T)
print(arr.transpose())
print('--------------------------------')
#Reversal
#Reversing entire 2D array( in both axes)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('original array',arr_2d)
reversed_arr = np.flip(arr_2d)
print('Reversed Array',reversed_arr)
reversed_arr_rows = np.flip(arr_2d, axis=0)
print('Reversed Rows only',reversed_arr_rows)
reversed_arr_columns = np.flip(arr_2d, axis=1)
print('Reversed Col Only', reversed_arr_columns)
#Reversing specific row alone
print('Reversing specific row',np.flip(arr_2d[1]))
#Reversing specific column alone
print('Reversing Specific Column',np.flip(arr_2d[:,1]))
print('Reversing single column',arr_2d)

Original Array [[0 1 2]
 [3 4 5]]
Transposed Array [[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
--------------------------------
original array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed Array [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reversed Rows only [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed Col Only [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Reversing specific row [8 7 6 5]
Reversing Specific Column [10  6  2]
Reversing single column [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Multi Dimensional Arrays**

In [ ]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape
c[1, ...]  # same as c[1, :, :] or c[1]
b=c[1,:,2]  # same as c[:, :, 2]
print(b) # shape will be [,2]
np.shape(b) # why it is not retriving the shape as [2,]? as i am choosing the colums only?
b=c[1,1,2:] #Now the shape will be [2,]
print(b)
print(np.shape(b))

#Iterating through  ND arrays with respect to first axis
for row in c:
    print(row)

#Iterating by flattening the arrays
for element in b.flat:
    print(element)

[102 113]
[113]
(1,)
[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]
113


**Reshaping and Flattening of ND arrays**

In [ ]:
x = np.array([[1 ,2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#using flatten(doesnt affect original array 'X')
a1=x.flatten()
print('Flatten', a1)
#using ravel(affect the original array 'X')
a2=x.ravel()
print('Ravel',a2)
#reshape -> doesnt modify the input array
y = np.array([[1 ,2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Reshaped',y.reshape(6,2))
print('Reshaped',y) #doesnt affect original

#using resize-> affects original
y = np.array([[1 ,2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y.resize(6,2)
print('Resized',y)

#using Transpose
print('Transpose',y.T)




Flatten [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Reshaped [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Resized [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Transpose [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


**Help Documentation**

In [ ]:
#help documentation using help function
help(np.unique)
#using  ipython(?) command
np.unique?
a=np.arange(6)
a?
#We can also read the source code of the inbuilt function using ?? operation
np.unique??


Help on _ArrayFunctionDispatcher in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the sp

Working with Mathematical Formulas

In [ ]:
#Implement Mean Square Error  Formula
# Mean Square Error = (1/n) * np.sum(np.square(predictions - labels ))

**Saving and loading NumPy Objects**

In [ ]:
a = np.arange(6)
#saving single nD array to .npy file
print(a)
np.save('single_Array_binary',a)
#load the file to reconstruct the array
np.load('single_Array_binary.npy')

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

Storing multiple arrays zipped (.npz format )

In [ ]:
#method 1 <passing each array in the arugment
# Create some sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[10, 20], [30, 40]])
array3 = np.arange(12).reshape((3, 4))

# Save the arrays to a .npz file
np.savez('my_arrays.npz', arr_one=array1, arr_two=array2, arr_three=array3)

# Load the .npz file and access the arrays
loaded_arrays = np.load('my_arrays.npz')

# Print the names of the arrays in the .npz file
print("Arrays in .npz file:", loaded_arrays.files)

# Access and print the loaded arrays
print("\nLoaded array 'arr_one':\n", loaded_arrays['arr_one'])
print("\nLoaded array 'arr_two':\n", loaded_arrays['arr_two'])
print("\nLoaded array 'arr_three':\n", loaded_arrays['arr_three'])

#demonstrating that the loaded arrays are indeed numpy arrays.
print(type(loaded_arrays['arr_one']))

# Method 2 creating a dictionary and loading the arrays
arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7,8,9])]
names = ["array1", "array2", "array3"]

# Create a dictionary of arrays
array_dict = {names[i]: arrays[i] for i in range(len(arrays))}

# Save the dictionary to a .npz file
np.savez('my_arrays.npz', **array_dict)

# Load the .npz file
loaded_arrays = np.load('my_arrays.npz')

# Print the loaded arrays
print(loaded_arrays.files)
for name in names:
    print(loaded_arrays[name])

Arrays in .npz file: ['arr_one', 'arr_two', 'arr_three']

Loaded array 'arr_one':
 [1 2 3 4 5]

Loaded array 'arr_two':
 [[10 20]
 [30 40]]

Loaded array 'arr_three':
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>
['array1', 'array2', 'array3']
[1 2 3]
[4 5 6]
[7 8 9]


**Loading .csv or .txt file**The savetxt() and loadtxt() functions accept additional optional parameters such as header, footer, and delimiter. While text files can be easier for sharing, .npy and .npz files are smaller and faster to read

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype = 'int32')
print(csv_arr)
np.savetxt('csv_file.csv', csv_arr, fmt='%d') #save the format as integer
np.loadtxt('csv_file.csv', dtype='int32') #load the file as integer

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

**More plays on indexing**

In [ ]:
#Indexing with Single Dimension
a = np.arange(12)**2  # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])  # an array of indices
print(a[i])  # It prints the elements of `a` at the positions `i`

j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
print(a[j])  # it prints the element of a at position 'i' with the same shape as `j`

#Indexing with multi dimension
#When the source array 'b' is multidimensional,
#a single array of indices 'i' refers to the first dimension of 'b'
b = np.arange(12).reshape(3, 4)
#original array
i=np.array([1,2,2])
print('Multi dim. orginal',b)
print('Multi dim. indexing',b[i])

#when the array 'b' is multi dimensional and i is also multi dimension
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color(row) in the palette
                  [0, 3, 4, 0]])
print('Pallet with Image',palette[image])
print('-----------------------------------------------------------')
#When the array 'b' is multi dimensional, we are passing i, j and
#both are multi dimensional
a = np.arange(12).reshape(3, 4)
print('original Array',a)
i = np.array([[0, 1],  # indices for the first dim of `a`
              [1, 2]])
j = np.array([[2, 1],  # indices for the second dim
              [3, 3]])

#Here it consideres i & j as co.orinates by iteration
#eg. a[i[0,0],j[0,0]] = a[0,2] =2
#a[i[0, 1], j[0, 1]] = a[1, 1] = 5
#a[i[1, 0], j[1, 0]] = a[1, 3] = 7
#a[i[1, 1], j[1, 1]] = a[2, 3] = 11
#so output will be [[2,5],[7,11]
a[i, j]  # i and j must have equal shape
a[i, 2]
a[:, j]




[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]
Multi dim. orginal [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Multi dim. indexing [[ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]
Pallet with Image [[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]
-----------------------------------------------------------
original Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

**Advanced Indexing tricks**

In [ ]:
#searching max value of a series


**Importing and exporting a CSV**

< We will cover in Pandas>

**Plotting Arrays with MatplotLib**

In [ ]:
#< We will cover in MatplotLib>

SyntaxError: invalid syntax (<ipython-input-1-f145e37599f8>, line 1)

**2D array create Functions**

In [ ]:
#1. np.eye()
# when i = j ( row and column index are equal) prints 1 else 0.
import numpy as np
print(np.eye(3))
print(np.eye(3, 5))

#2. np.diag()
# passing values in the diagonals of the array
print(np.diag([1,2,3]))
a= np.array([[1,2],[3,4]])
print(np.diag(a)) #prints the diagonal elements of a
#diagonal with offset value
print(np.diag([1,2,3]))
print(np.diag([1, 2, 3], 1)) #here 1 is offset, so it prints one diagonal above the main diagonal

#3.np.vander()-> Vandermore Matrix

np.vander(np.linspace(0, 2, 5), 2)
#for the input array, 2 columns will be created
#column1-> power of 1
#column2-> 1( anything power 0 = 1)
np.vander([1, 2, 3, 4], 2)
#for input array, 4 columns will be created
#column1->power of 3;
#column2->power of 2
#column1->power of 1
#column1->power of 0( always 1)
np.vander((1, 2, 3, 4), 4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 4]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
